const nodemailer = require('nodemailer');

/**
 * Sends a success notification email via Gmail SMTP using nodemailer.
 * @param {Object} post - The published post object.
 * @returns {Promise<void>}
 */
const sendSuccessNotification = async (post) => {
  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_APP_PASSWORD;
  const recipient = process.env.NOTIFICATION_EMAIL;

  if (!gmailUser || !gmailPass || !recipient) {
    console.log('[Notification Service] Gmail credentials or recipient email not configured. Skipping email notification.');
    return;
  }

  // Set up the transporter
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: gmailUser,
      pass: gmailPass
    }
  });

  const mailOptions = {
    from: `"LinkFlow Automation" <${gmailUser}>`,
    to: recipient,
    subject: '🚀 LinkFlow Post Successfully Published to LinkedIn!',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e4e7; border-radius: 12px; background-color: #fbfaf7; color: #333;">
        <h2 style="color: #08060d; border-bottom: 2px solid #aa3bff; padding-bottom: 10px; margin-top: 0;">🚀 LinkFlow Notification</h2>
        <p style="font-size: 14px; line-height: 1.6;">Hello!</p>
        <p style="font-size: 14px; line-height: 1.6;">Your scheduled post has been successfully published to your LinkedIn profile.</p>
        
        <div style="background-color: #fff; padding: 15px; border-radius: 8px; border: 1px solid #e5e4e7; margin: 20px 0;">
          <h4 style="margin: 0 0 10px 0; color: #6b6375; font-size: 12px; text-transform: uppercase; letter-spacing: 1px;">Post Caption</h4>
          <p style="margin: 0; font-size: 14px; line-height: 1.5; white-space: pre-wrap; font-style: italic; color: #555;">${post.text}</p>
        </div>

        ${post.postUrl ? `
        <div style="margin: 25px 0 15px 0; text-align: center;">
          <a href="${post.postUrl}" target="_blank" style="background-color: #aa3bff; color: #ffffff; text-decoration: none; padding: 12px 24px; font-weight: bold; border-radius: 25px; display: inline-block; font-size: 14px; box-shadow: 0 4px 6px rgba(170, 59, 255, 0.25);">View Live Update on LinkedIn</a>
        </div>
        <p style="font-size: 12px; text-align: center; color: #888;">If the button doesn't work, copy this link: <br/><a href="${post.postUrl}" style="color: #aa3bff;">${post.postUrl}</a></p>
        ` : ''}

        <hr style="border: 0; border-top: 1px solid #e5e4e7; margin: 30px 0 15px 0;" />
        <p style="font-size: 11px; text-align: center; color: #888; margin: 0;">This email was automatically generated by LinkFlow Secured Agent.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('[Notification Service] Success notification sent via Gmail. Message ID:', info.messageId);
  } catch (err) {
    console.error('[Notification Service] Failed to send Gmail notification:', err.message);
  }
};

module.exports = { sendSuccessNotification };
